name: Test APT Repository
on:
    workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install repo
        uses: gerlero/add-apt-repository@v1
        with:
          uri: https://bishiboosh.github.io/test-debian-repo/
          suite: stable
          key: https://bishiboosh.github.io/test-debian-repo/gpg.key
      - name: Install package
        run: |
          sudo apt update
          sudo apt install -y caupain
      - name: Launch package
        run: |
          which caupain
          caupain --version