name: Test APT Repository
on:
    workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install repo
        run: |
          sudo mkdir -p /usr/share/keyrings/  
          curl -sfLo /usr/share/keyrings/caupain.gpg.key https://bishiboosh.github.io/test-debian-repo/gpg.key
          echo "deb [signed-by=/usr/share/keyrings/caupain.gpg.key] https://bishiboosh.github.io/test-debian-repo/ stable main" > sudo tee -a /etc/apt/sources.list.d/caupain.list
          
      - name: Install package
        run: |
          sudo apt update
          sudo apt install -y caupain
      - name: Launch package
        run: |
          which caupain
          caupain --version